# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qyzasgZdD7BfqeZWXpFwBx7NHG5_gkO-
"""

#2
hour = input("Quantas horas você trabalhou? ")
minutes = input("Quantos minutos você trabalhou? ")
seconds = input("Quantos segundos você trabalhou? ")
print(hour + ":" , minutes + ":" , seconds)

#4
Ingredient = input("Qual é o primeiro ingrediente para omelete? ")
Ingredient1 = input("Ok, qual mais? ")
Ingredient2 = input("Blz, mais algum? ")

print("Ingredientes: " , Ingredient + ", " + Ingredient1 + ", " + Ingredient2)

#1
name = input("Digite seu nome ")
print(name + "? Nossa! Que nome feio kkkk")

#3

Ingredient = input("Qual é o primeiro ingrediente para omelete? ")
Ingredient1 = input("Ok, qual mais? ")
Ingredient2 = input("Blz, mais algum? ")

print("Ingredientes:" , Ingredient)
print(Ingredient1)
print(Ingredient2)

#5

Adjective = input("Escreva uma qualidade sua: ")
Adjective1 = input("Mais uma: ")
Adjective2 = input("Só mais uma: ")
print(Adjective + ", " + Adjective1, "e " + Adjective2+".", "Você parece ser uma pessoa interessante!")